pipeline:
  build:
    image: library/debian:unstable
    commands: 
      - apt-get update
      - apt-get -y dist-upgrade
      - apt-get -y install devscripts software-properties-common
      - apt-add-repository 'deb https://www.dsscaw.com/repos/apt/debian unstable main'
      - apt-key add debian/9EA957D484A4266A.asc
      - apt-get update
      - apt-get install libblossom-dev
      - autoreconf -fis
      - ./configure
      - make -j8
      - make check
