pipeline:
  build:
    image: library/debian:unstable
    commands: 
      - apt-get update
      - apt-get -y remove man-db # ees so slow, updating zee manpage database :/
      - apt-get -y dist-upgrade
      - apt-get -y install devscripts git-buildpackage
      - mk-build-deps --install -t'apt-get -y'
      - autoreconf -fis
      - ./configure
      - make -j8
      - make check
